import "./globals.css";
import { Inter } from "next/font/google";
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Quarta entrega",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <header className="bg-gray-700 text-white">
          <div>
            <h2>MEUS PRODUTOS</h2>
            <ul>
              <li className="inline">
                <Link href="/">Home</Link>
              </li>
              <li className="inline">
                <Link href="/produtos/tenis">Tênis</Link>
              </li>
              <li className="inline">
                <Link href="/produtos/meia">Meia</Link>
              </li>
              <li className="inline">
                <Link href="/produtos/camisa">Camisa</Link>
              </li>
              <li className="inline">
                <Link href="/produtos/calca">Calça</Link>
              </li>
            </ul>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
